def print_grid(grid, padding=0):
    if isinstance(grid, list):
        ...
    elif isinstance(grid, dict):
        ...
    elif isinstance(grid, set):
        ...
    elif isinstance(grid, tuple):
        ...


def print_list(grid): ...
